android {
    namespace = "com.example.auto_reel_maker"
    compileSdk = 34  // <-- ISKO 34 KARNA SABSE IMPORTANT HAI

    sourceSets {
        getByName("main") {
            java.srcDirs("src/main/kotlin")
        }
    }

    defaultConfig {
        applicationId = "com.example.auto_reel_maker"
        minSdk = 24
        targetSdk = 34  // <-- ISKO BHI 34 KAR DE
        versionCode = flutter.versionCode
        versionName = flutter.versionName
    }